### ISSUE TITLE
website not online

### ISSUE THREAD

**Issue by obaidazeino** [obaidazeino/html-validation-fixes#1]
could you tell me whether file and folder name changes get sent to github or is it just the code?
@anna-pokhilenko

**Comment by obaidazeino** [comment]
website not online
@abhaysharma

**Comment by abhaysharma** [comment]
@obaidazeino the issue is with the file name. Your index.html is Index.html which breaks the link.

**Comment by obaidazeino** [comment]
@abhaysharma It is correct on my computer and pushed
no matter what I do it stays capitalized on github

**Comment by obaidazeino** [comment]
everything worked thank you
